// src/pages/discover/Search.vue
<template>
  <div :class="getClass">
    <Input
      placeholder="Search podcast"
      @focus="$parent.$emit('keyboard', true)"
      @blur="$parent.$emit('keyboard', false)"
    />
    <div class="input-shadow"></div>
    <div class="expanded"></div>
  </div>
</template>

<script>
import Component from '~scripts/component'

export default new Component({
  name: 'Search',
  data() {
    return {
      active: false,
    }
  },
})
</script>

<style lang="scss" scoped>
@import '~/styles/shadows';
$trans: 0.2s linear;

.search {
  width: 100%;
  height: 100%;
  padding-top: 0.5rem;
  padding-bottom: 0.5rem;

  .input {
    width: 100%;
    margin: 0;
    border: none;
    height: 100%;
  }

  .input-shadow {
    box-shadow: none;
    pointer-events: none;
  }

  .expanded {
    z-index: 3000;
    position: absolute;
    top: 100%;
    width: 100%;
    left: 0;
    background-color: white;
    height: 0;
    display: block;
    transition: height $trans, transform $trans, width $trans,
      box-shadow 0s linear 0.2s;
    box-shadow: none;
  }
  .input:focus ~ .expanded {
    transform: none;
    width: 100%;
    height: calc(100vh - 8rem);
    box-shadow: shadow(4);
    transition: height $trans, transform $trans, width $trans, box-shadow 0s;
  }
}

.merged > .search {
  .input-shadow {
    position: relative;
    width: 100%;
    height: 100%;
    display: block;
    transform: translateY(-100%);
    box-shadow: shadow(2);
    border-radius: 0.25rem;
    transition: transform $trans, width $trans, height $trans,
      border-radius 0s 0.2s;
  }

  .input:focus ~ .input-shadow {
    transform: translateX(-1rem) translateY(calc(-100% + 0.5rem));
    width: calc(100% + 2rem);
    height: calc(100% + 1rem);
    border-radius: 0;
    transition: transform $trans, width $trans, height $trans, border-radius 0s;
  }

  .expanded {
    width: calc(100% - 2rem);
    transform: translateX(1rem) translateY(-0.5rem);
  }
}
</style>

// src/components/organisms/appbar/Search.tsx
import React from 'react'
import styled from 'styled-components'
import { IconButton, Input } from '~/components/atoms'
import { withRouter } from 'react-router-dom'
import { RouteComponentProps } from 'react-router'
import { layout, shadow } from '~/styles'

interface Props extends RouteComponentProps {
  align: 'left' | 'right'
}

interface State {
  expanded: boolean
}

class Search extends React.Component<Props, State> {
  state = {
    expanded: false,
  }
  expandedRef: React.RefObject<HTMLDivElement>

  constructor(props) {
    super(props)
    this.expandedRef = React.createRef()
  }

  render() {
    return (
      <S.Search className={`action ${this.props.align}`}>
        <IconButton icon="search" onClick={() => this.toggleExpand()} />
        <S.Expanded
          ref={this.expandedRef}
          className={[...(this.state.expanded ? ['active'] : [])].join(' ')}
        >
          <IconButton
            icon={this.state.expanded ? 'arrow_back' : 'search'}
            onClick={() => this.toggleExpand()}
          />
          <Input placeholder="Search podcast" />
          <S.ResultPane />
        </S.Expanded>
      </S.Search>
    )
  }

  toggleExpand() {
    if (!this.state.expanded) {
      this.setState({ expanded: true })
      setTimeout(
        () => this.expandedRef.current.querySelector('input').focus(),
        200
      )
    } else {
      this.setState({ expanded: false })
    }
  }
}
export default withRouter(Search)

namespace S {
  const transitionTime = '0.2s'

  export const Search = styled.div`
    display: block;
  `

  export const Expanded = styled.div`
    position: absolute;
    transition: all 1s;
    top: 0;
    height: 100%;
    width: 100%;
    transition: transform ${transitionTime} ease,
      visibility 0s ${transitionTime};
    visibility: hidden;
    display: flex;
    flex-direction: row;
    align-items: center;
    background-color: ${({ theme }) => theme[theme.topic](theme.variant).color};
    transition-delay: ${transitionTime};

    input,
    svg {
      transition: transform ${transitionTime} ease;
    }

    input {
      margin-left: 1rem;
      opacity: 0;
    }

    &.active {
      visibility: visible;
      transition: transform ${transitionTime} ease;
      transition-delay: 0s;
      box-shadow: ${shadow(2)};

      // @ts-ignore
      ${({ forwardedRef: { current: ref } }) => {
        if (!ref) return
        return `
          transform: translateX(${-ref.offsetLeft}px);

          input, svg {
            transform: translateX(1rem);
          }

          input {
            opacity: 1;
            transition: none;
          }
        `
      }}
    }
  `

  export const ResultPane = styled.div`
    position: absolute;
    display: block;
    top: 100%;
    visibility: hidden;
    width: 100%;
    left: 0;
    background-color: inherit;
    height: 2rem;
    transition: all ${transitionTime} ease;
    box-shadow: ${shadow(1)};
    z-index: -1;

    .active > & {
      transition-delay: ${transitionTime};
      visibility: visible;
      height: calc(100vh - 100% - ${layout.mobile.navHeight});
    }
  `
}
