// src/components/organisms/Mainnav.jsx
import React from 'react'
import styled from 'styled-components'
import { shadow, responsive, layout } from '~/styles'
import Item from './mainnav/Item'

export default class Mainnav extends React.Component {
  constructor(props) {
    super(props)
  }

  render() {
    return (
      <Bar responsive={responsive} layout={layout}>
        <Item to="/" icon="library">
          Library
        </Item>
        <Item to="/feed" icon="subscriptions">
          Feed
        </Item>
        <Item to="/discover" icon="search">
          Discover
        </Item>
        <Item to="/profile" icon="person">
          Profile
        </Item>
      </Bar>
    )
  }
}

const Bar = styled.div`
  position: fixed;
  box-sizing: border-box;
  bottom: 0;
  width: 100vw;
  height: 4rem;
  display: block;
  background-color: white;
  box-shadow: ${shadow(4)};

  display: flex;
  flex-direction: row;
  justify-content: space-around;
  align-items: center;

  @media ${({ responsive }) => responsive.navOnSide} {
    height: 100vh;
    width: ${({ layout }) => layout.desktop.navWidth};
    flex-direction: column;
    justify-content: flex-start;
    align-items: flex-start;
    padding-left: 1.5rem;
    padding-top: 2rem;

    .menu-item {
      margin-bottom: 2rem;
    }
  }
`

// src/components/molecular/MainNav.vue
<template>
  <div :class="{...getClassObj, fixed}" :style="fixPos">
    <Icon name="library" @click="$router.push('/podcasts')"></Icon>
    <Icon name="feed" @click="$router.push('/')"></Icon>
    <Icon name="search" @click="$router.push('/')"></Icon>
    <Icon name="account" @click="$router.push('/profile')"></Icon>
  </div>
</template>

<script>
import Component from '~/scripts/component'

export default new Component({
  name: 'MainNav',
  props: {
    fixed: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    fixPos() {
      return !this.fixed || !this.$el ? {} : { top: `${this.$el.offsetTop}px` }
    },
  },
})
</script>

<style lang="scss" scoped>
@import '~/styles/shadows';

.main-nav {
  background-color: white;
  height: 4rem;
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-around;
  align-items: center;
  box-shadow: shadow(7);

  position: fixed;
  bottom: 0;

  .icon {
    cursor: pointer;
  }

  &:not(.fixed) {
    @media (orientation: landscape) {
      width: 5rem;
      height: 100%;
      flex-direction: column;
    }
  }
}
</style>
