// src/components/molecular/Player.vue
<template>
  <div :class="getClass">
    <audio crossorigin="anonymous" src="https://traffic.libsyn.com/hellointernet/126.mp3"></audio>
    <div class="controls">
      <PlayButton v-model="playState"></PlayButton>
    </div>
  </div>
</template>

<script>
import Component from '~scripts/component'
import PlayButton from './player/PlayButton'

export default new Component({
  name: 'Player',
  components: {
    PlayButton,
  },
  data() {
    return {
      audioContext: new (window.AudioContext || window.webkitAudioContext)(),
      playState: false,
      track: null,
      audioElement: null,
    }
  },
  watch: {
    playState(v) {
      if (this.audioContext.state === 'suspended') {
        this.audioContext.resume()
      }
      if (v) this.audioElement.play()
      else this.audioElement.pause()
    },
  },
  mounted() {
    this.audioElement = this.$el.querySelector('audio')
    this.track = this.audioContext.createMediaElementSource(this.audioElement)
    this.track.connect(this.audioContext.destination)
  },
})
</script>

<style lang="scss" scoped>
@import '~/styles/shadows';

.player {
  width: 100%;
  height: 4rem;
  background-color: white;
  box-sizing: border-box;
  border-bottom: 1px solid rgba(#000, 8%);
  box-shadow: shadow(7);

  position: fixed;
  bottom: 4rem;

  display: flex;
  flex-direction: row;
  justify-content: space-between;

  .controls {
    height: 100%;
    display: flex;
    flex-direction: row;
    flex-grow: 1;
    justify-content: space-around;
    align-items: center;
  }

  @media (orientation: landscape) {
    bottom: 0;
  }
}
</style>

// src/components/organisms/Player.tsx
import React from 'react'
import styled, { ThemeProvider } from 'styled-components'
import { layout, shadow, responsive, timing } from '~/styles'
import { useSelector, useDispatch } from 'react-redux'
import State from '~/store/state'
import { togglePlaying } from '~/store/actions'
import PlayButton from './player/PlayButton'
import { useMatchMedia } from '~/utils/hooks'

export default function Player() {
  const visible = useSelector((state: State) => state.player.visible)
  const dispatch = useDispatch()
  const navOnSide = useMatchMedia(responsive.navOnSide)

  function pause() {
    dispatch(togglePlaying(false))
  }

  function play() {
    dispatch(togglePlaying(true))
  }

  return (
    <ThemeProvider theme={{ topic: 'surface', variant: navOnSide ? 1 : 0 }}>
      {visible && (
        <S.Player>
          <PlayButton togglePlayer={v => (v ? play() : pause())} />
        </S.Player>
      )}
    </ThemeProvider>
  )
}

const S = {
  Player: styled.div`
    display: flex;
    justify-content: space-around;
    align-items: center;
    z-index: 1900;
    position: fixed;
    bottom: ${layout.mobile.navHeight};
    width: 100vw;
    height: ${layout.mobile.playerHeight};
    ${({ theme }) =>
      theme.elevationMode === 'shadow' ? `box-shadow: ${shadow(2)};` : ''}
    background-color: ${({ theme }) => theme[theme.topic](theme.variant).color};
    transition: background-color ${() => timing.colorSwap};

    @media ${responsive.navOnSide} {
      bottom: 0;
      height: ${layout.desktop.playerHeight};
      z-index: 2100;
    }
  `,
}
